// Generated by CoffeeScript 1.6.2
var adaptAppXmlFile, deepExtend, _ref;

_ref = require('flash-build-api').utils, adaptAppXmlFile = _ref.adaptAppXmlFile, deepExtend = _ref.deepExtend;

module.exports = function(data, root, version, air, target, onComplete) {
  if (data.inputDescriptor && data.descriptor) {
    return adaptAppXmlFile(data.inputDescriptor, data.descriptor, data.mainFile, root, version, data["app-id"], function(error, result) {
      if (error) {
        return onComplete(error);
      } else {
        data['app-id'] = result.id;
        if (result.version) {
          data.version = result.version;
        }
        data = deepExtend(data, air);
        data.target = target;
        return onComplete(null, data);
      }
    });
  } else {
    return onComplete(null, data);
  }
};
