// Generated by CoffeeScript 1.6.2
var flashAPI;

flashAPI = require('flash-build-api');

module.exports = {
  createAppXmlIfNecessary: require('./createAppXmlIfNecessary'),
  parseProject: require('./parseProject')
};
